### ISSUE TITLE
Error: Nonetype object has no attribute 'text'

### ISSUE THREAD

**Issue by veerukumar28** [FarhanRehman/HQ-BOT-#2]
![Screenshot_2019-10-11-06-46-55-99_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/55420342/66617856-7476c880-ebf4-11e9-9c77-17e90e8b5ee6.png)

getting this error plz try to solve

**Comment by vishu002** [comment]
how to get bearer token
